"""`ralph pr` — create a GitHub PR from the run branch via the gh CLI."""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

from rich.console import Console

from .config import RalphConfig
from .prd import PRD
from . import cost_tracker
from . import progress as prog

console = Console()

_SUMMARY_RE = re.compile(
    r"## \[[^\]]+\] Story (\S+):[^\n]*\n✅ DONE\nSummary: ([^\n]+)"
)


def _story_summaries(progress_text: str) -> dict[str, str]:
    """Latest DONE summary per story id from progress.txt."""
    summaries: dict[str, str] = {}
    for m in _SUMMARY_RE.finditer(progress_text):
        summaries[m.group(1)] = m.group(2).strip()
    return summaries


def build_pr_body(prd: PRD, ralph_dir: Path) -> str:
    progress_text = prog.read(ralph_dir / "progress.txt")
    summaries = _story_summaries(progress_text)
    total_cost = cost_tracker.total_cost(ralph_dir / "cost.log")
    stats = prd.stats()

    lines = [prd.description, "", "## Stories", ""]
    for story in prd.stories:
        if story.passes:
            summary = summaries.get(story.id, "")
            suffix = f" — {summary}" if summary else ""
            lines.append(f"- ✅ `{story.id}` {story.title}{suffix}")
        elif story.failed:
            lines.append(f"- ❌ `{story.id}` {story.title} (failed/skipped)")
        else:
            lines.append(f"- ⏳ `{story.id}` {story.title} (pending)")

    lines += [
        "",
        "## Run Stats",
        "",
        f"- {stats['done']}/{stats['total']} stories completed",
        f"- Total cost: ${total_cost:.2f}",
        "",
        "---",
        "Generated by [Ralph](https://github.com/Markol06/myRalphie)",
    ]
    return "\n".join(lines)


def create_pr(project_root: Path, draft: bool = False) -> bool:
    """Push the run branch and open a PR against base_branch. Returns success."""
    ralph_dir = project_root / ".ralph"
    prd = PRD.load(ralph_dir / "prd.json")
    config = RalphConfig.load(project_root)

    gh = shutil.which("gh")
    if not gh:
        console.print("[red]gh CLI not found.[/red] Install it: https://cli.github.com")
        return False
    if not prd.branch_name:
        console.print("[red]prd.json has no branch_name — nothing to open a PR from.[/red]")
        return False

    console.print(f"[dim]Pushing {prd.branch_name} to origin...[/dim]")
    push = subprocess.run(
        ["git", "push", "-u", "origin", prd.branch_name],
        cwd=project_root, capture_output=True, text=True, timeout=120,
    )
    if push.returncode != 0:
        console.print(f"[red]git push failed:[/red]\n{push.stderr.strip()}")
        return False

    body_file = ralph_dir / "pr_body.md"
    body_file.write_text(build_pr_body(prd, ralph_dir), encoding="utf-8")

    cmd = [
        gh, "pr", "create",
        "--title", prd.project_name,
        "--body-file", str(body_file),
        "--base", config.base_branch,
        "--head", prd.branch_name,
    ]
    if draft:
        cmd.append("--draft")

    r = subprocess.run(cmd, cwd=project_root, capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        console.print(f"[red]gh pr create failed:[/red]\n{r.stderr.strip()}")
        return False

    console.print(f"[bold green]PR created:[/bold green] {r.stdout.strip()}")
    return True
